import { createTheme } from "@mui/material/styles";
import { useTheme } from "./stores/themeStore";

/**
 * Material You (Material Design 3) seeded palette for CloudTune.
 * Generated from the NetEase red seed (#C20C0C) for both light and dark
 * schemes. Surfaces use the neutral tonal palette; accents use the
 * primary tonal palette. Components are tuned to match MD3 elevation,
 * shape, and state layering.
 */

// Simplified MD3 tonal palette derived from the NetEase red seed (#C20C0C).
// In a production app these would be generated by @material/material-color-utilities.
const tones = {
  primary: ["#fff8f7", "#ffdad7", "#ffb4ab", "#ff897d", "#ff5449", "#de3730", "#ba1a1a", "#93000a", "#690005", "#410002"],
  secondary: ["#fff8f7", "#f7dedc", "#e6beba", "#d5a099", "#c4867f", "#a96c66", "#8e5650", "#73413c", "#592c28", "#3e1815"],
  tertiary: ["#fffbff", "#eed9e4", "#d1bec9", "#b5a2af", "#998894", "#806f7b", "#665662", "#4d3e4a", "#362833", "#20131d"],
  neutral: ["#fffbff", "#f2eeed", "#e4e0df", "#d6d2d1", "#c9c5c4", "#a09c9b", "#777371", "#5f5c5b", "#474443", "#302d2d", "#1a1818"],
  neutralVariant: ["#fffbff", "#f0e0df", "#e2c4c2", "#c4a8a6", "#a88d8b", "#8d7472", "#735b59", "#5a4442", "#422e2c", "#2b1918"],
  error: ["#fffbff", "#ffdad6", "#ffb4ab", "#ff897a", "#ff5449", "#de3730", "#ba1a1a", "#93000a", "#690005", "#410002"],
};

const light = {
  primary: tones.primary[5],
  onPrimary: tones.primary[0],
  primaryContainer: tones.primary[1],
  onPrimaryContainer: tones.primary[9],
  secondary: tones.secondary[6],
  onSecondary: tones.secondary[0],
  secondaryContainer: tones.secondary[1],
  onSecondaryContainer: tones.secondary[9],
  surface: tones.neutral[0],
  surfaceDim: tones.neutral[1],
  surfaceBright: "#fff8f7",
  surfaceContainerLowest: "#ffffff",
  surfaceContainerLow: "#f7f2f2",
  surfaceContainer: tones.neutral[1],
  surfaceContainerHigh: tones.neutral[2],
  surfaceContainerHighest: tones.neutral[3],
  onSurface: tones.neutral[10],
  onSurfaceVariant: tones.neutralVariant[7],
  outline: tones.neutralVariant[6],
  outlineVariant: tones.neutralVariant[1],
  error: tones.error[5],
  onError: tones.error[0],
  scrim: "rgba(0,0,0,0.32)",
};

const dark = {
  primary: tones.primary[2],
  onPrimary: tones.primary[8],
  primaryContainer: tones.primary[7],
  onPrimaryContainer: tones.primary[1],
  secondary: tones.secondary[2],
  onSecondary: tones.secondary[8],
  secondaryContainer: tones.secondary[6],
  onSecondaryContainer: tones.secondary[1],
  surface: tones.neutral[10],
  surfaceDim: "#181616",
  surfaceBright: tones.neutral[8],
  surfaceContainerLowest: "#151313",
  surfaceContainerLow: "#1a1818",
  surfaceContainer: "#201a1a",
  surfaceContainerHigh: "#2b2323",
  surfaceContainerHighest: "#362e2e",
  onSurface: "#f0dedd",
  onSurfaceVariant: "#d8c2bf",
  outline: "#a08c8a",
  outlineVariant: "#534342",
  error: tones.error[2],
  onError: tones.error[8],
  scrim: "rgba(0,0,0,0.64)",
};

function buildTheme(mode: "light" | "dark") {
  const t = mode === "light" ? light : dark;
  return createTheme({
    palette: {
      mode,
      primary: { main: t.primary, contrastText: t.onPrimary },
      secondary: { main: t.secondary, contrastText: t.onSecondary },
      background: { default: t.surface, paper: t.surfaceContainer },
      text: { primary: t.onSurface, secondary: t.onSurfaceVariant },
      error: { main: t.error, contrastText: t.onError },
      divider: t.outlineVariant,
    },
    shape: { borderRadius: 16 },
    typography: {
      fontFamily:
        '"Noto Sans SC Variable", "PingFang SC", "Microsoft YaHei", system-ui, sans-serif',
      h4: { fontWeight: 700, letterSpacing: "-0.02em" },
      h6: { fontWeight: 600, letterSpacing: "-0.01em" },
      subtitle2: { fontWeight: 600 },
      button: { textTransform: "none", fontWeight: 600 },
    },
    components: {
      MuiListItemButton: {
        styleOverrides: {
          root: {
            borderRadius: 999,
            minHeight: 40,
            "&.Mui-selected": {
              backgroundColor: t.secondaryContainer,
              color: t.onSurface,
              "&:hover": { backgroundColor: t.secondaryContainer },
            },
          },
        },
      },
      MuiPaper: {
        styleOverrides: { root: { backgroundImage: "none" } },
      },
      MuiTooltip: {
        styleOverrides: {
          tooltip: {
            backgroundColor: t.surfaceContainerHighest,
            color: t.onSurface,
            borderRadius: 8,
          },
        },
      },
      MuiIconButton: {
        styleOverrides: {
          root: {
            borderRadius: "50%",
          },
        },
      },
      MuiSlider: {
        styleOverrides: {
          root: {
            color: t.primary,
          },
        },
      },
    },
  });
}

export function useAppTheme() {
  const effective = useTheme((s) => s.effective);
  return buildTheme(effective);
}

export const tokens = { light, dark };
